framework:
    secret: '%env(APP_SECRET)%'
    # API stateless : pas de session côté serveur.
    session: false
    http_method_override: false
    handle_all_throwables: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
